version: "3"
services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - redisdata:/data
    command: redis-server --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: "exit 0"
      interval: 1s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - redis_network

volumes:
  redisdata: {}

networks:
  redis_network:
