version: "3"
services:
  #  It is for the intel chips
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   container_name: mssql
  #   # volumes:
  #     # - mssqlvolume:/var/opt/mssql
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "Maf#58c4"
  #   ports:
  #     - 1433:1433

  # For M series chips

  mssqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssqledge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Maf#58c4"
    ports:
      - 1433:1433
    volumes:
      - mssqlvolume:/var/opt/mssql
    networks:
      - mssqledge_network

volumes:
  mssqlvolume: {}

networks:
  mssqledge_network:
    # external: true
